# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170208_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
