# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_games_url'),
        ('shop', '0007_auto_20170218_1925'),
    ]

    operations = [
    ]
