# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170218_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='confcode',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
